version: '2'
services:
  mysql:
    image: mysql:5.6
    restart: always
    container_name: mysql_5.6
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=root"
      - "TZ=Asia/Shanghai"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --max_connections=3000
    ports:
      - 3307:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./log:/var/log/mysql
      - ./conf:/etc/mysql/conf.d
    networks:
      - myweb

networks:
  myweb:
    driver: bridge